<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();

    $_product->setDoNotUseCategoryId(false);
    $stars = $_product->getStars();
    $tovar = $block->getTovar();
    $_product->setTovar($tovar);
    $printPrice = $_product->getPrintPrice();
?>
<?php if($tovar):?>
<div class="product-info-main">
    <div class="page-title-wrapper product">
        <h1 class="page-title"><?php echo $tovar->getName();?> <?php echo $_product->getName();?></h1>
    </div>
    <!--<div class="product-code"><span><?php echo $tovar->getSku().'-'.$_product->getSku();?></span></div>
    <div class="product-favorite">
        <div class="action-secondary"><span>Избранное</span>
            <button data-post='<?php /* echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product, ['tovar' => $tovar->getId()]) */?>' class="action towishlist secondary"
               data-action="add-to-wishlist"><span class="label">Избранное</span></button>
        </div>
    </div>-->


    <?php if($stars > 0) :?>
        <div class="product-rating-summary">
            <div class="rating-summary">
                <div class="rating-result rating-transparent">
                    <?php for ($rate = 20; $rate <= 100; $rate += 20): ?>
                        <a href="#rate-product" class="rating-action <?php if ($rate <= $stars) echo 'active' ?>"></a>
                    <?php endfor; ?>
                    <div class="rating-loader"></div>
                </div>
            </div>
        </div>
    <?php endif;?>
    <div class="product-info-price">
        <?php echo $printPrice;?>
    </div>

    <div class="product-add-form">
        <form data-product-sku="<?php echo $block->escapeHtml($tovar->getSku()) ?>"
              action="<?php echo $block->escapeHtml($block->getSubmitUrl($tovar)) ?>" method="post"
              id="product_addtocart_form"<?php if ($tovar->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $tovar->getId() ?>" />
            <input type="hidden" name="selected_configurable_option" value="" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            <input type="hidden" name="print" value="<?php echo $_product->getId();?>" />
            <?php echo $block->getBlockHtml('formkey');?>
            <?php echo $block->getChildHtml('form_top'); ?>

            <?php //echo $block->getChildHtml('swatches'); ?>

            <div class="product-options-wrapper" id="product-options-wrapper">
                <div class="fieldset">
                    <?php
                        if($tovar->getTypeId() == "configurable"){
                            $block->getChildBlock('swatches')->setTovar($tovar);
                            echo $block->getChildHtml('swatches');
                        }
                    ?>
                    <?php
                        $block->getChildBlock('options_size')->setTovar($tovar);
                        echo $block->getChildHtml('options_size');
                    ?>
                </div>
            </div>



            <input name="qty" type="hidden" value="1" />
            <div class="product-options-bottom">
                <div class="actions">
                    <div class="actions-primary">
                        <button type="submit" disabled class="action tocart primary"><span>В корзину</span></button>
                    </div>
                    <div class="actions-primary">
                        <button type="button" class="action click-buy primary" data-name="<?php echo $_product->getProductUrl() ?>?tovar=<?php echo $tovar->getSku();?>"><span>Купить в 1 клик</span></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <script>
        require([
            'jquery',
            'priceBox'
        ], function($){
            var dataPriceBoxSelector = '[data-role=priceBox]',
                dataProductIdSelector = '[data-product-id=<?php echo $block->escapeHtml($_product->getId())?>]',
                priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

            priceBoxes = priceBoxes.filter(function(index, elem){
                return !$(elem).find('.price-from').length;
            });

            priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
        });
    </script>

    <div class="product-desc">
        <div class="actions"><a class="product-related" href="#modal-relevant-product">Другие товары с этим принтом</a></div>
        <div class="product-desc-text">
            <?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $tovar->getDescription(), 'description') ?>

        </div>
    </div>
</div>
<?php else:?>
    <p class="error">Товар не найден</p>
<?php endif;?>